In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('../data/processed/base_tratada.csv')
base.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [3]:
# Convertendo a coluna InvoiceDate para o tipo datetime
base['InvoiceDate'] = pd.to_datetime(base['InvoiceDate'])

In [4]:
# Para criar o RFM, precisa de uma data de referência
data_referencia = base['InvoiceDate'].max() 
print(data_referencia)

2011-12-09 12:50:00

In [5]:
Recency = data_referencia

In [6]:
# Criar tabela RFM
rfm = base.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (Recency - x.max()).days,  
    'InvoiceNo': 'nunique',
    'TotalPrice': 'sum'
    })
rfm.columns = ['Recency', 'Frequency', 'Monetary']

In [7]:
print(rfm.head())

            Recency  Frequency  Monetary
CustomerID
12346           325          1  77183.60
12347             1          7   4310.00
12348            74          4   1797.24
12349            18          1   1757.55
12350           309          1    334.40

In [9]:
# Ver as informações estatísticas da tabela RFM
print(rfm.describe())
print(rfm.info())

           Recency    Frequency       Monetary
count  4338.000000  4338.000000    4338.000000
mean     91.536422     4.272015    2054.266460
std     100.014169     7.697998    8989.230441
min       0.000000     1.000000       3.750000
25%      17.000000     1.000000     307.415000
50%      50.000000     2.000000     674.485000
75%     141.000000     5.000000    1661.740000
max     373.000000   209.000000  280206.020000
<class 'pandas.core.frame.DataFrame'>
Index: 4338 entries, 12346 to 18287
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Recency    4338 non-null   int64
 1   Frequency  4338 non-null   int64
 2   Monetary   4338 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 135.6 KB
None

In [10]:
# Resetar o índice
rfm.reset_index(inplace=True)
rfm.head()

   CustomerID  Recency  Frequency  Monetary
0       12346      325          1  77183.60
1       12347        1          7   4310.00
2       12348       74          4   1797.24
3       12349       18          1   1757.55
4       12350      309          1    334.40

In [12]:
# Salvar a base RFM em um arquivo CSV
rfm.to_csv('../data/processed/rfm_clientes.csv', index=False)